/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.*;
import java.beans.PropertyVetoException;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;
import java.awt.event.ItemListener;
import javax.swing.ImageIcon;

/**
 *
 * @author Karlos
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setIcon();
        homeButton.setOpaque(false);
        registerStudentButton.setOpaque(false);
        registerProfessorButton.setOpaque(false);
        manageStudentButton.setOpaque(false);
        manageProfessorButton.setOpaque(false);
        aboutButton.setOpaque(false);
    }

    public void setColor(JPanel panel) {
        panel.setBackground(new Color(255,255,255));
    }
 
    public void resetColor(JPanel panel) {
        panel.setBackground(new Color(204,204,204));
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        iconHome = new javax.swing.JLabel();
        registerStudentButton = new javax.swing.JPanel();
        txtRegStud = new javax.swing.JLabel();
        studentIcon = new javax.swing.JLabel();
        registerProfessorButton = new javax.swing.JPanel();
        txtRegProf = new javax.swing.JLabel();
        professorIcon = new javax.swing.JLabel();
        manageStudentButton = new javax.swing.JPanel();
        txtManStud = new javax.swing.JLabel();
        manStudentIcon = new javax.swing.JLabel();
        manageProfessorButton = new javax.swing.JPanel();
        txtManProf = new javax.swing.JLabel();
        manProfessorIcon = new javax.swing.JLabel();
        aboutButton = new javax.swing.JPanel();
        txtAbout = new javax.swing.JLabel();
        aboutIcon = new javax.swing.JLabel();
        homeButton = new javax.swing.JPanel();
        txtSchool = new javax.swing.JLabel();
        homeIcon = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();
        xPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JLabel();
        screen = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("School Manager");
        setBackground(new java.awt.Color(204, 204, 204));
        setFocusTraversalPolicyProvider(true);
        setUndecorated(true);

        backPanel.setBackground(new java.awt.Color(255, 255, 255));
        backPanel.setForeground(new java.awt.Color(204, 204, 204));

        sidePanel.setBackground(new java.awt.Color(204, 204, 204));

        iconHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/black/icon_book.png"))); // NOI18N

        registerStudentButton.setBackground(new java.awt.Color(204, 204, 204));
        registerStudentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerStudentButtonMousePressed(evt);
            }
        });

        txtRegStud.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtRegStud.setForeground(new java.awt.Color(0, 0, 0));
        txtRegStud.setText("Register Student");

        studentIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/black/icon_student.png"))); // NOI18N

        javax.swing.GroupLayout registerStudentButtonLayout = new javax.swing.GroupLayout(registerStudentButton);
        registerStudentButton.setLayout(registerStudentButtonLayout);
        registerStudentButtonLayout.setHorizontalGroup(
            registerStudentButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerStudentButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRegStud)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registerStudentButtonLayout.setVerticalGroup(
            registerStudentButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerStudentButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerStudentButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(registerStudentButtonLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(studentIcon))
                    .addComponent(txtRegStud, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap())
        );

        registerProfessorButton.setBackground(new java.awt.Color(204, 204, 204));
        registerProfessorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerProfessorButtonMousePressed(evt);
            }
        });

        txtRegProf.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtRegProf.setForeground(new java.awt.Color(0, 0, 0));
        txtRegProf.setText("Register Professor");

        professorIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/black/icon_professor.png"))); // NOI18N

        javax.swing.GroupLayout registerProfessorButtonLayout = new javax.swing.GroupLayout(registerProfessorButton);
        registerProfessorButton.setLayout(registerProfessorButtonLayout);
        registerProfessorButtonLayout.setHorizontalGroup(
            registerProfessorButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerProfessorButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(professorIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRegProf)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registerProfessorButtonLayout.setVerticalGroup(
            registerProfessorButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerProfessorButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerProfessorButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(registerProfessorButtonLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(professorIcon))
                    .addComponent(txtRegProf, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap())
        );

        manageStudentButton.setBackground(new java.awt.Color(204, 204, 204));
        manageStudentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageStudentButtonMousePressed(evt);
            }
        });

        txtManStud.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtManStud.setForeground(new java.awt.Color(0, 0, 0));
        txtManStud.setText("Manage Student");

        manStudentIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/black/icon_manageStudent.png"))); // NOI18N

        javax.swing.GroupLayout manageStudentButtonLayout = new javax.swing.GroupLayout(manageStudentButton);
        manageStudentButton.setLayout(manageStudentButtonLayout);
        manageStudentButtonLayout.setHorizontalGroup(
            manageStudentButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageStudentButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manStudentIcon)
                .addGap(18, 18, 18)
                .addComponent(txtManStud)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        manageStudentButtonLayout.setVerticalGroup(
            manageStudentButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageStudentButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageStudentButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtManStud, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(manStudentIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        manageProfessorButton.setBackground(new java.awt.Color(204, 204, 204));
        manageProfessorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageProfessorButtonMousePressed(evt);
            }
        });

        txtManProf.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtManProf.setForeground(new java.awt.Color(0, 0, 0));
        txtManProf.setText("Manage Professor");

        manProfessorIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/black/icon_manageProfessor.png"))); // NOI18N

        javax.swing.GroupLayout manageProfessorButtonLayout = new javax.swing.GroupLayout(manageProfessorButton);
        manageProfessorButton.setLayout(manageProfessorButtonLayout);
        manageProfessorButtonLayout.setHorizontalGroup(
            manageProfessorButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageProfessorButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manProfessorIcon)
                .addGap(18, 18, 18)
                .addComponent(txtManProf)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        manageProfessorButtonLayout.setVerticalGroup(
            manageProfessorButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageProfessorButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageProfessorButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtManProf, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(manProfessorIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        aboutButton.setBackground(new java.awt.Color(204, 204, 204));
        aboutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aboutButtonMousePressed(evt);
            }
        });

        txtAbout.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtAbout.setForeground(new java.awt.Color(0, 0, 0));
        txtAbout.setText("About");

        aboutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/black/icon_about.png"))); // NOI18N

        javax.swing.GroupLayout aboutButtonLayout = new javax.swing.GroupLayout(aboutButton);
        aboutButton.setLayout(aboutButtonLayout);
        aboutButtonLayout.setHorizontalGroup(
            aboutButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aboutIcon)
                .addGap(18, 18, 18)
                .addComponent(txtAbout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        aboutButtonLayout.setVerticalGroup(
            aboutButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aboutIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(txtAbout, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        homeButton.setBackground(new java.awt.Color(204, 204, 204));
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeButtonMousePressed(evt);
            }
        });

        txtSchool.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtSchool.setForeground(new java.awt.Color(0, 0, 0));
        txtSchool.setText("School Manager ");

        homeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/black/icon_home.png"))); // NOI18N

        javax.swing.GroupLayout homeButtonLayout = new javax.swing.GroupLayout(homeButton);
        homeButton.setLayout(homeButtonLayout);
        homeButtonLayout.setHorizontalGroup(
            homeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeIcon)
                .addGap(18, 18, 18)
                .addComponent(txtSchool)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homeButtonLayout.setVerticalGroup(
            homeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSchool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homeIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap())
        );

        separator.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerStudentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(registerProfessorButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageStudentButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageProfessorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(aboutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(separator)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(iconHome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(iconHome)
                .addGap(18, 18, 18)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(registerStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerProfessorButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageProfessorButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aboutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        xPanel.setBackground(new java.awt.Color(204, 204, 204));
        xPanel.setPreferredSize(new java.awt.Dimension(25, 25));

        closeButton.setBackground(new java.awt.Color(0, 0, 0));
        closeButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        closeButton.setForeground(new java.awt.Color(0, 0, 0));
        closeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeButton.setText("X");
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout xPanelLayout = new javax.swing.GroupLayout(xPanel);
        xPanel.setLayout(xPanelLayout);
        xPanelLayout.setHorizontalGroup(
            xPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanelLayout.createSequentialGroup()
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        xPanelLayout.setVerticalGroup(
            xPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        screen.setBackground(new java.awt.Color(255, 255, 255));
        screen.setForeground(new java.awt.Color(255, 255, 255));
        screen.setPreferredSize(new java.awt.Dimension(459, 376));

        javax.swing.GroupLayout screenLayout = new javax.swing.GroupLayout(screen);
        screen.setLayout(screenLayout);
        screenLayout.setHorizontalGroup(
            screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );
        screenLayout.setVerticalGroup(
            screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backPanelLayout = new javax.swing.GroupLayout(backPanel);
        backPanel.setLayout(backPanelLayout);
        backPanelLayout.setHorizontalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backPanelLayout.createSequentialGroup()
                        .addComponent(screen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );
        backPanelLayout.setVerticalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addComponent(xPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(screen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerStudentButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerStudentButtonMousePressed
        
        resetColor(homeButton);
        setColor(registerStudentButton);
        resetColor(registerProfessorButton);
        resetColor(manageStudentButton);
        resetColor(manageProfessorButton);
        resetColor(aboutButton);
        homeButton.setOpaque(false);
        registerStudentButton.setOpaque(true);
        registerProfessorButton.setOpaque(false);
        manageStudentButton.setOpaque(false);
        manageProfessorButton.setOpaque(false);
        aboutButton.setOpaque(false);
        
        RegisterStudent rs = new RegisterStudent();
        screen.add(rs).setVisible(true);
        rs.setBackground(new Color(255, 255, 255));                     
    }//GEN-LAST:event_registerStudentButtonMousePressed

    private void closeButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMousePressed
        System.exit(0);
    }//GEN-LAST:event_closeButtonMousePressed

    private void registerProfessorButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerProfessorButtonMousePressed
       
        resetColor(homeButton);
        resetColor(registerStudentButton);
        setColor(registerProfessorButton);
        resetColor(manageStudentButton);
        resetColor(manageProfessorButton);
        resetColor(aboutButton);
        homeButton.setOpaque(false);
        registerStudentButton.setOpaque(false);
        registerProfessorButton.setOpaque(true);
        manageStudentButton.setOpaque(false);
        manageProfessorButton.setOpaque(false);
        aboutButton.setOpaque(false);
        
        RegisterProfessor rp = new RegisterProfessor();
        screen.add(rp).setVisible(true);
        rp.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_registerProfessorButtonMousePressed

    private void manageStudentButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageStudentButtonMousePressed
        
        resetColor(homeButton);
        resetColor(registerStudentButton);
        resetColor(registerProfessorButton);
        setColor(manageStudentButton);
        resetColor(manageProfessorButton);
        resetColor(aboutButton);
        homeButton.setOpaque(false);
        registerStudentButton.setOpaque(false);
        registerProfessorButton.setOpaque(false);
        manageStudentButton.setOpaque(true);
        manageProfessorButton.setOpaque(false);
        aboutButton.setOpaque(false);
        
        ManageStudent ms = new ManageStudent();
        screen.add(ms).setVisible(true);
        ms.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_manageStudentButtonMousePressed

    private void manageProfessorButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageProfessorButtonMousePressed
        
        resetColor(homeButton);
        resetColor(registerStudentButton);
        resetColor(registerProfessorButton);
        resetColor(manageStudentButton);
        setColor(manageProfessorButton);
        resetColor(aboutButton);
        homeButton.setOpaque(false);
        registerStudentButton.setOpaque(false);
        registerProfessorButton.setOpaque(false);
        manageStudentButton.setOpaque(false);
        manageProfessorButton.setOpaque(true);
        aboutButton.setOpaque(false);
        
        ManageProfessor mp = new ManageProfessor();
        screen.add(mp).setVisible(true);
        mp.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_manageProfessorButtonMousePressed

    private void aboutButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutButtonMousePressed
        

        resetColor(homeButton);
        resetColor(registerStudentButton);
        resetColor(registerProfessorButton);
        resetColor(manageStudentButton);
        resetColor(manageProfessorButton);
        setColor(aboutButton);
        homeButton.setOpaque(false);
        registerStudentButton.setOpaque(false);
        registerProfessorButton.setOpaque(false);
        manageStudentButton.setOpaque(false);
        manageProfessorButton.setOpaque(false);
        aboutButton.setOpaque(true);  

        About ab = new About();
        screen.add(ab).setVisible(true);
        ab.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_aboutButtonMousePressed

    private void homeButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMousePressed
        JInternalFrame[] frames = screen.getAllFrames();
            for (JInternalFrame frame : frames) {
                try {
                    frame.setClosed(true);
                } catch (PropertyVetoException e) {
                    e.printStackTrace();
                }
                
            }
      
        setColor(homeButton);
        resetColor(registerStudentButton);
        resetColor(registerProfessorButton);
        resetColor(manageStudentButton);
        resetColor(manageProfessorButton);
        resetColor(aboutButton);
        homeButton.setOpaque(true);
        registerStudentButton.setOpaque(false);
        registerProfessorButton.setOpaque(false);
        manageStudentButton.setOpaque(false);
        manageProfessorButton.setOpaque(false);
        aboutButton.setOpaque(false);       
    }//GEN-LAST:event_homeButtonMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon_book.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutButton;
    private javax.swing.JLabel aboutIcon;
    private javax.swing.JPanel backPanel;
    private javax.swing.JLabel closeButton;
    private javax.swing.JPanel homeButton;
    private javax.swing.JLabel homeIcon;
    private javax.swing.JLabel iconHome;
    private javax.swing.JLabel manProfessorIcon;
    private javax.swing.JLabel manStudentIcon;
    private javax.swing.JPanel manageProfessorButton;
    private javax.swing.JPanel manageStudentButton;
    private javax.swing.JLabel professorIcon;
    private javax.swing.JPanel registerProfessorButton;
    private javax.swing.JPanel registerStudentButton;
    private javax.swing.JDesktopPane screen;
    private javax.swing.JSeparator separator;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel studentIcon;
    private javax.swing.JLabel txtAbout;
    private javax.swing.JLabel txtManProf;
    private javax.swing.JLabel txtManStud;
    private javax.swing.JLabel txtRegProf;
    private javax.swing.JLabel txtRegStud;
    private javax.swing.JLabel txtSchool;
    private javax.swing.JPanel xPanel;
    // End of variables declaration//GEN-END:variables
}
