/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Model.Professor;
import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Karlos
 */
public class RegisterProfessor extends javax.swing.JInternalFrame {
    public final Professor professor;
    /**
     * Creates new form RegisterProfessor
     */
    public RegisterProfessor() {
        professor = new Professor();
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wageProfessorField = new javax.swing.JTextField();
        txtId = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        txtAge = new javax.swing.JLabel();
        txtDiscipline = new javax.swing.JLabel();
        txtWage = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        nameProfessorField = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        idProfessorField = new javax.swing.JTextField();
        ageProfessorField = new javax.swing.JTextField();
        disciplineProfessorField = new javax.swing.JTextField();

        wageProfessorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wageProfessorFieldActionPerformed(evt);
            }
        });

        txtId.setText("ID:");

        txtName.setText("NAME:");

        txtAge.setText("AGE:");

        txtDiscipline.setText("DISCIPLINE:");

        txtWage.setText("WAGE:");

        cancelButton.setBackground(new java.awt.Color(255, 153, 153));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(0, 0, 0));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        nameProfessorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameProfessorFieldActionPerformed(evt);
            }
        });

        confirmButton.setBackground(new java.awt.Color(204, 255, 204));
        confirmButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(0, 0, 0));
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        idProfessorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idProfessorFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtId)
                    .addComponent(txtName)
                    .addComponent(txtAge)
                    .addComponent(txtDiscipline)
                    .addComponent(txtWage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameProfessorField)
                    .addComponent(disciplineProfessorField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idProfessorField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageProfessorField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wageProfessorField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idProfessorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameProfessorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageProfessorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAge))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disciplineProfessorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiscipline))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wageProfessorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(confirmButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void wageProfessorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wageProfessorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wageProfessorFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        idProfessorField.setText("");
        nameProfessorField.setText("");
        ageProfessorField.setText("");        
        disciplineProfessorField.setText("");        
        wageProfessorField.setText("");        
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void nameProfessorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameProfessorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameProfessorFieldActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
       try {
            int id = 0;
            String name = "";
            int age = 0;
            int wage = 0;
            String discipline = "";
            
            if(Integer.parseInt(this.idProfessorField.getText()) < 0) {
                throw new Messages("ID must be a number and cannot be 0");
            } else {
                id = Integer.parseInt(this.idProfessorField.getText());
            }
            
            if(this.nameProfessorField.getText().length() < 2) {
                throw new Messages("The name must contain at least 2 characters");
            } else {
                name = this.nameProfessorField.getText();
            }
            
            if(Integer.parseInt(this.ageProfessorField.getText()) <= 0) {
                throw new Messages("Age must be a number and be greater than 0");
            } else {
                age = Integer.parseInt(this.ageProfessorField.getText());
            }
            
            if(Integer.parseInt(this.wageProfessorField.getText()) < 1000) {
                throw new Messages("The wage must be at least 1000");
            } else {
                wage = Integer.parseInt(this.wageProfessorField.getText());
            }
            
            if(this.disciplineProfessorField.getText().length() < 2) {
                throw new Messages("Discipline must contain at least 2 characters");
            } else {
                discipline = this.disciplineProfessorField.getText();
            }
            
            try {
                if(this.professor.insertProfessorDB(name, age, id, wage, discipline)) {
                    JOptionPane.showMessageDialog(null,"Successfully registered professor!");
                    professor.getProfessor().toString();
                    
                    this.idProfessorField.setText("");
                    this.nameProfessorField.setText("");
                    this.ageProfessorField.setText("");        
                    this.disciplineProfessorField.setText("");        
                    this.wageProfessorField.setText(""); 
                } else {
                    JOptionPane.showMessageDialog(null, "Error to Instert professor!");
                }
            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            
        } catch (Messages e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void idProfessorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idProfessorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idProfessorFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageProfessorField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField disciplineProfessorField;
    private javax.swing.JTextField idProfessorField;
    private javax.swing.JTextField nameProfessorField;
    private javax.swing.JLabel txtAge;
    private javax.swing.JLabel txtDiscipline;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtWage;
    private javax.swing.JTextField wageProfessorField;
    // End of variables declaration//GEN-END:variables
}
