/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Model.Student;
import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Karlos
 */
public class RegisterStudent extends javax.swing.JInternalFrame {
    public final Student student;
    /**
     * Creates new form RegisterStudent
     */
    public RegisterStudent() {
        this.student = new Student();
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameStudentField = new javax.swing.JTextField();
        idStudentField = new javax.swing.JTextField();
        ageStudentField = new javax.swing.JTextField();
        courseStudentField = new javax.swing.JTextField();
        stageStudentField = new javax.swing.JTextField();
        txtId = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        txtAge = new javax.swing.JLabel();
        txtCourse = new javax.swing.JLabel();
        txtStage = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();

        nameStudentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameStudentFieldActionPerformed(evt);
            }
        });

        idStudentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idStudentFieldActionPerformed(evt);
            }
        });

        stageStudentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stageStudentFieldActionPerformed(evt);
            }
        });

        txtId.setText("ID:");

        txtName.setText("NAME:");

        txtAge.setText("AGE:");

        txtCourse.setText("COURSE:");

        txtStage.setText("STAGE:");

        cancelButton.setBackground(new java.awt.Color(255, 153, 153));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(0, 0, 0));
        cancelButton.setText("Cancel");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelButtonMousePressed(evt);
            }
        });
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        confirmButton.setBackground(new java.awt.Color(204, 255, 204));
        confirmButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(0, 0, 0));
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtId)
                    .addComponent(txtName)
                    .addComponent(txtAge)
                    .addComponent(txtCourse)
                    .addComponent(txtStage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameStudentField)
                    .addComponent(courseStudentField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idStudentField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageStudentField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stageStudentField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idStudentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameStudentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageStudentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAge))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseStudentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCourse))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stageStudentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(confirmButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idStudentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idStudentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idStudentFieldActionPerformed

    private void nameStudentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameStudentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameStudentFieldActionPerformed

    private void stageStudentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stageStudentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stageStudentFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        try {
            int id = 0;
            String name = "";
            int age = 0;
            String course = "";
            int stage = 0;
            
            if(Integer.parseInt(this.idStudentField.getText()) < 0) {
                throw new Messages("ID must be a number and cannot be 0");
            } else {
                id = Integer.parseInt(this.idStudentField.getText());
            }
            
            if(this.nameStudentField.getText().length() < 2) {
                throw new Messages("The name must contain at least 2 characters");
            } else {
                name = this.nameStudentField.getText();
            }
            
            if(Integer.parseInt(this.ageStudentField.getText()) <= 0) {
                throw new Messages("Age must be a number and be greater than 0");
            } else {
                age = Integer.parseInt(this.ageStudentField.getText());
            }
            
            if(this.courseStudentField.getText().length() < 2) {
                throw new Messages("The course must contain at least 2 characters");
            } else {
                course = this.courseStudentField.getText();
            }
            
            if(Integer.parseInt(this.stageStudentField.getText()) < 0) {
                throw new Messages("Stage must be a number and cannot be 0");
            } else {
                stage = Integer.parseInt(this.stageStudentField.getText());
            }
            
            try {
                if(this.student.insertStudentDB(name, age, id, course, stage)) {
                    JOptionPane.showMessageDialog(null,"Successfully registered student!");
                    student.getStudent().toString();
                    
                    this.idStudentField.setText("");
                    this.nameStudentField.setText("");
                    this.ageStudentField.setText("");       
                    this.courseStudentField.setText("");       
                    this.stageStudentField.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "Error to Instert student!");
                }
            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            
        } catch (Messages e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void cancelButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMousePressed
        idStudentField.setText("");
        nameStudentField.setText("");
        ageStudentField.setText("");       
        courseStudentField.setText("");       
        stageStudentField.setText("");
    }//GEN-LAST:event_cancelButtonMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageStudentField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField courseStudentField;
    private javax.swing.JTextField idStudentField;
    private javax.swing.JTextField nameStudentField;
    private javax.swing.JTextField stageStudentField;
    private javax.swing.JLabel txtAge;
    private javax.swing.JLabel txtCourse;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtStage;
    // End of variables declaration//GEN-END:variables

}
